[package]
name = "discovery"
version = "0.1.0"
edition = "2021"
authors = ["Maxim Tugunchinov <tugunchinov.maxim@gmail.com>"]
description = "TODO"

[dependencies.messages]
path = "../messages"

[dependencies.settings]
path = "../settings"
[dependencies]
log = "0.4.20"